# Generated by Django 5.1.1 on 2024-09-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_doctor_speciality_doctor_availability"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialty",
            fields=[
                ("spec_id", models.AutoField(primary_key=True, serialize=False)),
                ("spec_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Speciality",
        ),
    ]
