# Generated by Django 5.1.1 on 2024-09-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_specialty_alter_doctor_availability_and_more'),
        ('user', '0003_rename_wallet_user_wallet_id_user_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
