# Generated by Django 5.1.1 on 2024-09-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('availability', models.JSONField(default={'friday': [], 'interval': 20, 'monday': [], 'saturday': [], 'sunday': [], 'thursday': [], 'tuesday': [], 'wednesday': []})),
            ],
        ),
    ]
