# Generated by Django 5.1.1 on 2024-09-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default={'friday': [], 'interval': 20, 'monday': [], 'saturday': [], 'sunday': [], 'thursday': [], 'tuesday': [], 'wednesday': []}),
        ),
    ]
