# Generated by Django 5.1.1 on 2024-09-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0002_remove_doctor_speciality_doctor_availability"),
        ("user", "0002_specialty_delete_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="specialty",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.specialty",
            ),
            preserve_default=False,
        ),
    ]
