# Generated by Django 5.1.1 on 2024-09-13 15:28

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_rename_speciality_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default=doctor.models.default_availability),
        ),
    ]
