# Generated by Django 5.1.1 on 2024-09-19 14:16

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default=doctor.models.Doctor.availability_dict),
        ),
    ]
