# Generated by Django 5.1.1 on 2024-09-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_doctor_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('spec_id', models.AutoField(primary_key=True, serialize=False)),
                ('spec_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='availability',
            field=models.JSONField(default={'friday': [], 'interval': 20, 'monday': [], 'saturday': [], 'sunday': [], 'thursday': [], 'tuesday': [], 'wednesday': []}),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.specialty'),
        ),
    ]
